import { useEffect, useRef } from 'react';
import { useMutation } from '@apollo/client/react';
import { gql } from '@apollo/client';
import { usePrivy, useWallets } from '@privy-io/react-auth';
import { useDisconnect } from 'wagmi';

const ADD_USER = gql`
  mutation AddUser($email: String, $name: String, $signer_address: String!, $wallet_address: String) {
    addUser(email: $email, name: $name, signer_address: $signer_address, wallet_address: $wallet_address) {
      id
      email
      name
    }
  }
`;

export function useSyncUserToDB(
  smartAccountAddress: string | undefined
) {
  const { user, authenticated, logout } = usePrivy();
  const { wallets } = useWallets();
  const { disconnect } = useDisconnect();

  const connectedWallet = wallets[0]?.address;

  // Find the embedded wallet generated by Privy
  const embeddedWallet = user?.linkedAccounts?.find(
    (account) => account.type === 'wallet' && account.walletClientType === 'privy'
  );
  
  // @ts-ignore - type definitions might be tricky for Privy wallet
  const walletAddress = embeddedWallet?.address || (user?.wallet as any)?.address;
  const finalWalletAddress = walletAddress || connectedWallet;

  const [addUser] = useMutation(ADD_USER);

  // Prevent React Strict Mode double-firing and database spam while still allowing the Smart Account to save on the second pass
  const lastSyncedSmartAccount = useRef<string | undefined>(undefined);

  // Reset sync status if the user completely logs out
  useEffect(() => {
    if (!authenticated && !connectedWallet) {
      lastSyncedSmartAccount.current = undefined;
    }
  }, [authenticated, connectedWallet]);

  // Sync User to Database after connection
  useEffect(() => {
    // If the smart account state hasn't changed since the last sync, skip!
    if (lastSyncedSmartAccount.current === smartAccountAddress) return; 

    const isReadyToSync = finalWalletAddress && authenticated && user;

    if (isReadyToSync) {
      lastSyncedSmartAccount.current = smartAccountAddress; // Lock this specific state



      addUser({
        variables: {
          email: user?.email?.address || user?.google?.email || null,
          name: user?.google?.name || null,
          signer_address: finalWalletAddress,
          wallet_address: smartAccountAddress || null,
        }
      }).catch((e: any) => {
        console.error("Error saving user to DB:", e);
        alert(`Authentication Failed: ${e.message}`);
        if (authenticated) logout();
        if (connectedWallet) disconnect();
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [finalWalletAddress, smartAccountAddress, authenticated, user?.id]); // Trigger when any of these core states change!

  return { finalWalletAddress, connectedWallet };
}
